# longvarmeth pipeline tool versions
pipeline:
  name: 'longvarmeth'
  version: '0.2.1'
  nextflow_version: '24.04+'
tools:
  dorado: '0.9.6'
  minimap2: '2.26'
  samtools: '1.23.1'
  bcftools: '1.23.1'
  whatshap: '2.8'
  sniffles: '2.8.0'
  cnvkit: '0.9.13'
  modkit: '0.6.3'
  snpeff: '5.2'
  vep: '116.0'
  jbrowse2: '4.3.0'
  multiqc: '1.18'
  cramino: '0.13.0'
  fastqc: '0.12.1'
  nanoplot: '1.42.0'
  filtlong: '0.2.1'
  flye: '2.9.2'
  medaka: '1.8.0'
  quast: '5.2.0'
  busco: '5.5.0'
  pod5: '0.3.14'
  methylartist: '1.3.0'
  pysam: '0.21.0'

